services:
  mysql:
    image: mysql:8
    ports:
      - 14306:3306
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=oAJrASdzQE9r
      - MYSQL_USER=equipment
      - MYSQL_DATABASE=equipmentdata
    networks:
      - mysql_network

networks:
  mysql_network:
    driver: bridge